// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXLZ1G7j-6UZUpqVAOxwvY41ylP8fN64',
    appId: '1:982450847417:web:bdbbe0db69674ab3a6a568',
    messagingSenderId: '982450847417',
    projectId: 'mynotes-app-v1-92582',
    authDomain: 'mynotes-app-v1-92582.firebaseapp.com',
    storageBucket: 'mynotes-app-v1-92582.appspot.com',
    measurementId: 'G-5Y6RDDD4T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6A0U49RSZphtmsrk8oL76k-Zm5QJNnpc',
    appId: '1:982450847417:android:952a4c9c32ebad55a6a568',
    messagingSenderId: '982450847417',
    projectId: 'mynotes-app-v1-92582',
    storageBucket: 'mynotes-app-v1-92582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqiYS1BZJMsrHlxVEffbEcVMYIlLJesE',
    appId: '1:982450847417:ios:2701ba74ce329a8aa6a568',
    messagingSenderId: '982450847417',
    projectId: 'mynotes-app-v1-92582',
    storageBucket: 'mynotes-app-v1-92582.appspot.com',
    iosClientId: '982450847417-d7m8gdrarhihef2qcrh488daq2r9sslq.apps.googleusercontent.com',
    iosBundleId: 'com.hengkyasdev.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtqiYS1BZJMsrHlxVEffbEcVMYIlLJesE',
    appId: '1:982450847417:ios:2701ba74ce329a8aa6a568',
    messagingSenderId: '982450847417',
    projectId: 'mynotes-app-v1-92582',
    storageBucket: 'mynotes-app-v1-92582.appspot.com',
    iosClientId: '982450847417-d7m8gdrarhihef2qcrh488daq2r9sslq.apps.googleusercontent.com',
    iosBundleId: 'com.hengkyasdev.mynotes',
  );
}
